[Icon Theme]
Name=Emerald-Dark
Comment=Fresh and simple personality icon theme (dark version)
Inherits=Emerald,breese,ubuntu-mono-dark,faba,Humanlity,hicolor

Directories=actions/22,actions/24,animations/scalable

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/24]
Size=24
Context=Actions
Type=Fixed

[animations/scalable]
Size=22
Context=Actions
Type=Scalable


